# Regression Example in TensorFlow

Predicting house prices in Boston, Massachusetts

**Load Dependencies**

In [ ]:
import numpy as np
from tensorflow.keras.datasets import boston_housing
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization
from tensorflow.keras.callbacks import ModelCheckpoint
import os

**Load Data**

In [2]:
(X_train, y_train), (X_valid, y_valid) = boston_housing.load_data()

57026/57026 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [3]:
X_train.shape

(404, 13)

In [4]:
X_valid.shape

(102, 13)

In [5]:
X_train[0]

array([  1.23247,   0.     ,   8.14   ,   0.     ,   0.538  ,   6.142  ,
        91.7    ,   3.9769 ,   4.     , 307.     ,  21.     , 396.9    ,
        18.72   ])

In [6]:
y_train[0]

np.float64(15.2)

**Design Neural Network architecture**

In [10]:
model = Sequential()

# Design Neural Network architecture

# 1st Hidden Layer
model.add(Dense(32, input_dim = 13, activation = 'relu'))
model.add(BatchNormalization())

# 2nd Hidden Layer
model.add(Dense(16, activation = 'relu'))
model.add(BatchNormalization())
model.add(Dropout(0.2))

# Output Layer
model.add(Dense(1, activation='linear'))

In [11]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 32)             │           448 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_2           │ (None, 32)             │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_3           │ (None, 16)             │            64 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 16)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,185 (4.63 KB)

 Trainable params: 1,089 (4.25 KB)

 Non-trainable params: 96 (384.00 B)

**Configure Model**

In [12]:
model.compile(loss='mean_squared_error', optimizer='adam',)

In [13]:
output_dir = 'model_output/'

In [14]:
run_name = 'regression_baseline'
output_path = output_dir + run_name

In [15]:
if not os.path.exists(output_path):
    os.makedirs(output_path)

In [ ]:
modelcheckpoint = ModelCheckpoint(
    output_path + '/weights.{epoch:02d}.weights.h5', # Save model weights every epoch
    save_weights_only=True
)

**Train!**

In [18]:
model.fit(X_train, y_train,
    batch_size=8, epochs=32, verbose=1,
    validation_data=(X_valid, y_valid),
    callbacks=[modelcheckpoint] # val loss will be saved in the modelcheckpoint file (val loss under 50 is good for this dataset!, 40 is great!)
)

Epoch 1/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 610.1053 - val_loss: 472.3769
Epoch 2/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 604.9827 - val_loss: 525.3101
Epoch 3/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 575.6207 - val_loss: 529.9103
Epoch 4/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 563.5801 - val_loss: 512.1301
Epoch 5/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 464.2198 - val_loss: 488.1291
Epoch 6/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 471.1029 - val_loss: 454.9176
Epoch 7/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 465.3617 - val_loss: 428.1122
Epoch 8/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 414.0048 - val_loss: 383.8699
Epoch 9/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 393.5210 - val_loss: 377.2321
Epoch 10/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 332.7404 - val_loss: 350.5305
Epoch 11/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 294.1263 - val_loss: 366.8624
Epoch 12/32
51/51 ━━━━━━━━━━━━

**Performing inference**

In [20]:
model.load_weights(output_path + '/weights.20.weights.h5')

In [21]:
X_valid[42]

array([  9.32909,   0.     ,  18.1    ,   0.     ,   0.713  ,   6.185  ,
        98.7    ,   2.2616 ,  24.     , 666.     ,  20.2    , 396.9    ,
        18.13   ])

In [22]:
y_valid[42]

np.float64(14.1)

In [23]:
model.predict(np.reshape(X_valid[42], (1, 13)))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step


array([[14.096712]], dtype=float32)