# Regression Example in TensorFlow

Predicting house prices in Boston, Massachusetts

**Load Dependencies**

In [1]:
import numpy as np
from tensorflow.keras.datasets import boston_housing
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization
from tensorflow.keras.callbacks import ModelCheckpoint
import os

**Load Data**

In [2]:
(X_train, y_train), (X_valid, y_valid) = boston_housing.load_data()

In [3]:
X_train.shape

(404, 13)

In [4]:
X_valid.shape

(102, 13)

In [5]:
X_train[0]

array([  1.23247,   0.     ,   8.14   ,   0.     ,   0.538  ,   6.142  ,
        91.7    ,   3.9769 ,   4.     , 307.     ,  21.     , 396.9    ,
        18.72   ])

In [6]:
y_train[0]

np.float64(15.2)

**Design Neural Network architecture**

In [7]:
model = Sequential()

# Design Neural Network architecture

# 1st Hidden Layer
model.add(Dense(32, input_dim = 13, activation = 'relu'))
model.add(BatchNormalization())

# 2nd Hidden Layer
model.add(Dense(16, activation = 'relu'))
model.add(BatchNormalization())
model.add(Dropout(0.2))

# Output Layer
model.add(Dense(1, activation='linear'))

c:\Users\51766\DeepLearning\.venv\lib\site-packages\keras\src\layers\core\dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [8]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           448 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization             │ (None, 32)             │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_1           │ (None, 16)             │            64 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 16)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,185 (4.63 KB)

 Trainable params: 1,089 (4.25 KB)

 Non-trainable params: 96 (384.00 B)

**Configure Model**

In [9]:
model.compile(loss='mean_squared_error', optimizer='nadam',)

In [10]:
output_dir = 'model_output/'

In [11]:
run_name = 'regression_baseline'
output_path = output_dir + run_name

In [12]:
if not os.path.exists(output_path):
    os.makedirs(output_path)

In [13]:
modelcheckpoint = ModelCheckpoint(
    output_path + '/weights.{epoch:02d}.weights.h5', # Save model weights every epoch
    save_weights_only=True
)

**Train!**

In [14]:
model.fit(X_train, y_train,
    batch_size=8, epochs=32, verbose=1,
    validation_data=(X_valid, y_valid),
    callbacks=[modelcheckpoint] # val loss will be saved in the modelcheckpoint file (val loss under 50 is good for this dataset!, 40 is great!)
)

Epoch 1/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 576.7078 - val_loss: 739.0423
Epoch 2/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 613.8277 - val_loss: 685.1745
Epoch 3/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 528.3959 - val_loss: 623.4111
Epoch 4/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 517.2834 - val_loss: 545.9679
Epoch 5/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 500.8504 - val_loss: 478.8654
Epoch 6/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 463.9933 - val_loss: 412.2079
Epoch 7/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 452.9171 - val_loss: 324.6827
Epoch 8/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 436.9656 - val_loss: 236.7048
Epoch 9/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 349.9137 - val_loss: 145.4150
Epoch 10/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 306.0270 - val_loss: 73.6745
Epoch 11/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 287.1592 - val_loss: 91.7524
Epoch 12/32
51/51 ━━━━━━━━━━━━━━

**Performing inference**

In [20]:
model.load_weights(output_path + '/weights.28.weights.h5')

In [21]:
X_valid[42]

array([  9.32909,   0.     ,  18.1    ,   0.     ,   0.713  ,   6.185  ,
        98.7    ,   2.2616 ,  24.     , 666.     ,  20.2    , 396.9    ,
        18.13   ])

In [22]:
y_valid[42]

np.float64(14.1)

In [23]:
model.predict(np.reshape(X_valid[42], (1, 13)))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step


array([[14.88321]], dtype=float32)