# Regression Example in TensorFlow (with Tensorboard)

Predicting house prices in Boston, Massachusetts

**Load Dependencies**

In [1]:
import numpy as np
from tensorflow.keras.datasets import boston_housing
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.callbacks import TensorBoard
import os

**Load Data**

In [2]:
(X_train, y_train), (X_valid, y_valid) = boston_housing.load_data()

In [3]:
X_train.shape

(404, 13)

In [4]:
X_valid.shape

(102, 13)

In [5]:
X_train[0]

array([  1.23247,   0.     ,   8.14   ,   0.     ,   0.538  ,   6.142  ,
        91.7    ,   3.9769 ,   4.     , 307.     ,  21.     , 396.9    ,
        18.72   ])

In [6]:
y_train[0]

np.float64(15.2)

**Design Neural Network architecture**

In [7]:
model = Sequential()

# Design Neural Network architecture

# 1st Hidden Layer
model.add(Dense(32, input_dim = 13, activation = 'relu'))
model.add(BatchNormalization())

# 2nd Hidden Layer
model.add(Dense(16, activation = 'relu'))
model.add(BatchNormalization())
model.add(Dropout(0.2))

# Output Layer
model.add(Dense(1, activation='linear'))

c:\Users\51766\DeepLearning\.venv\lib\site-packages\keras\src\layers\core\dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [8]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           448 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization             │ (None, 32)             │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_1           │ (None, 16)             │            64 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 16)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,185 (4.63 KB)

 Trainable params: 1,089 (4.25 KB)

 Non-trainable params: 96 (384.00 B)

**Configure Model**

In [9]:
model.compile(loss='mean_squared_error', optimizer='nadam',)

In [10]:
output_dir = 'model_output/'

In [11]:
run_name = 'regression_drop50'
output_path = output_dir + run_name

In [12]:
if not os.path.exists(output_path):
    os.makedirs(output_path)

In [13]:
modelcheckpoint = ModelCheckpoint(
    output_path + '/weights.{epoch:02d}.weights.h5', # Save model weights every epoch
    save_weights_only=True
)

In [14]:
tensorboard = TensorBoard(log_dir='logs/' + run_name) # Log directory for TensorBoard

**Train!**

In [15]:
model.fit(X_train, y_train,
    batch_size=8, epochs=32, verbose=1,
    validation_data=(X_valid, y_valid),
    callbacks=[modelcheckpoint, tensorboard] # val loss will be saved in the modelcheckpoint file (val loss under 50 is good for this dataset!, 40 is great!)
)

Epoch 1/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 549.2111 - val_loss: 696.1288
Epoch 2/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 592.1642 - val_loss: 625.4886
Epoch 3/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 533.6700 - val_loss: 584.4871
Epoch 4/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 530.3058 - val_loss: 556.3596
Epoch 5/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 472.0167 - val_loss: 514.0223
Epoch 6/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 484.5471 - val_loss: 499.3863
Epoch 7/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 489.0268 - val_loss: 436.3066
Epoch 8/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 387.1359 - val_loss: 424.4985
Epoch 9/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 397.0125 - val_loss: 312.3065
Epoch 10/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 368.1998 - val_loss: 286.0341
Epoch 11/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 273.9139 - val_loss: 261.3088
Epoch 12/32
51/51 ━━━━━━━━━━━━

**Performing inference**

In [16]:
model.load_weights(output_path + '/weights.28.weights.h5')

In [17]:
X_valid[42]

array([  9.32909,   0.     ,  18.1    ,   0.     ,   0.713  ,   6.185  ,
        98.7    ,   2.2616 ,  24.     , 666.     ,  20.2    , 396.9    ,
        18.13   ])

In [18]:
y_valid[42]

np.float64(14.1)

In [19]:
model.predict(np.reshape(X_valid[42], (1, 13)))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step


array([[11.713241]], dtype=float32)